### ISSUE TITLE
Errors with the new search feature and user.followed_mangas

### ISSUE THREAD

**Issue by Haris320** [Sibyl666/pytmangadex#3]
When I attempt to run the search method as shown in the basic usage, I end up with an error code that says
 `TypeError: 'async_generator' object is not iterable` and when I try to print the search result manually I get `<async_generator object Mangadex.search at 0x000001596F486C10>`. Also when I call `user.followed_mangas` I recieve `<bound method Mangadex.__clientFollowedmanga of <pytmangadex.Mangadex object at 0x000001CB128A0E80>>`. If this is not an error any help would be deeply appreciated.

**Comment by Sibyl666** [comment]
https://github.com/Sibyl666/pytmangadex#base Do it like example here. search method is a async generator so it should be in a async function.

**Comment by Haris320** [comment]
> https://github.com/Sibyl666/pytmangadex#base Do it like example here. search method is a async generator so it should be in a async function.

**Comment by Haris320** [comment]
Every time I run the search command as shown in the example, the program crashes because it is unable to access MangaDex (Error 502).
`import asyncio
from pytmangadex import Mangadex


client = Mangadex()
client.login("username", "password")


async def main():
    async for manga in client.search("isekai", 10):  # params: Search word, limit
        print(manga.title)  # Manga object


if __name__ == "__main__":
    asyncio.run(main())
`
The errors I get: `C:\Users\haris\AppData\Local\Programs\Python\Python39\python.exe C:/Python/Aqua/MangaDexAPI.py
Traceback (most recent call last):
  File "C:\Python\Aqua\MangaDexAPI.py", line 15, in <module>
    asyncio.run(main())
  File "C:\Users\haris\AppData\Local\Programs\Python\Python39\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\haris\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 642, in run_until_complete
    return future.result()
  File "C:\Python\Aqua\MangaDexAPI.py", line 10, in main
    async for manga in client.search("isekai", 10):  # params: Search word, limit
  File "C:\Users\haris\AppData\Local\Programs\Python\Python39\lib\site-packages\pytmangadex\__init__.py", line 324, in search
    raise Exception(f"Cant get results {resp.status_code}")
Exception: Cant get results 502

Process finished with exit code 1
`

> https://github.com/Sibyl666/pytmangadex#base Do it like example here. search method is a async generator so it should be in a async function.

**Comment by Sibyl666** [comment]
Yep i get this error too. It looks like mangadex kinda scuffed right now.

**Comment by Haris320** [comment]
> Yep i get this error too. It looks like mangadex kinda scuffed right now.

[https://mangadex.org/thread/371439]
Yep, looks like MangaDex has a lot of 502s lately and they are updating the servers and the API. Hopefully after the change your code should work much better with little change.

**Comment by Sibyl666** [comment]
It's good to know that cause of issue is mangadex. I thought all my library screwed up

**Comment by Haris320** [comment]
> It's good to know that cause of issue is mangadex. I thought all my library screwed up

It seems that MangaDex fixed itself and your search feature now works. Also, is there any way to get the URL's of the titles returned from the search? 

`client = Mangadex()
client.login("username", "password")

print(client.user.followed_mangas)`

Also user.followed_mangas returns <bound method Mangadex.__clientFollowedmanga of <pytmangadex.Mangadex object at 0x00000179907887C0>> instead of any followed manga titles. This may once again be a problem with the website but I want to make sure I am using it right.

**Comment by Sibyl666** [comment]
follwed mangas is a function. call it with ()
```python
print(client.user.followed_mangas())
```
client search returns manga object that has manga_id attribute. You can use it to get links
```python
async def main():
    async for manga in client.search("isekai", 10):
        print(f"https://mangadex.org/title/{manga.manga_id}/")
```

**Comment by Haris320** [comment]
> follwed mangas is a function. call it with ()
> 
> ```python
> print(client.user.followed_mangas())
> ```
> 
> client search returns manga object that has manga_id attribute. You can use it to get links
> 
> ```python
> async def main():
>     async for manga in client.search("isekai", 10):
>         print(f"https://mangadex.org/title/{manga.manga_id}/")
> ```

Thanks for the help. Another thing that I have found to be slightly off is when I did `client.login("username","password")`everything worked. However the second time I tried it with another account it kept getting the information from the account I tried out first, even though I changed the username and password to the new account. I am unable to get any information from accounts other than the first one I tried out.

**Comment by Sibyl666** [comment]
Because it saves the session once and then keeps using that session to avoid login every time. But more than one account is something that i didn't think. May fix it in the future. There should be session.txt where the package is just delete it then login to account you want

**Comment by Sibyl666** [comment]
Just released new version for pytmangadex and added newLogin parameter to the login function. you can try it

**Comment by Haris320** [comment]
> follwed mangas is a function. call it with ()
> 
> ```python
> print(client.user.followed_mangas())
> ```
> 
> client search returns manga object that has manga_id attribute. You can use it to get links
> 
> ```python
> async def main():
>     async for manga in client.search("isekai", 10):
>         print(f"https://mangadex.org/title/{manga.manga_id}/")
> ```

The search works and is able to retrieve the manga id's. However, the program always crashes and is never able to complete. I get some results then I get this error. Also if I do `async for manga in client.search("isekai", 10):` it prints every single search result instead of just 10.

```Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x0000017CC9879940>
Traceback (most recent call last):
  File "C:\Users\ahmed\AppData\Local\Programs\Python\Python39\lib\asyncio\proactor_events.py", line 116, in __del__
    self.close()
  File "C:\Users\ahmed\AppData\Local\Programs\Python\Python39\lib\asyncio\proactor_events.py", line 108, in close
    self._loop.call_soon(self._call_connection_lost, None)
  File "C:\Users\ahmed\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 746, in call_soon
    self._check_closed()
  File "C:\Users\ahmed\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 510, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed```

**Comment by Sibyl666** [comment]
That event loop error is because of aiohttp library so not something you should worry about. when the search finishes the ```python asyncio.run(main()) ``` closes the loop but aiohttp has some cleanup before the loop closes. And 10 stands there for how many requests will be made at the same time

**Comment by Haris320** [comment]
> That event loop error is because of aiohttp library so not something you should worry about. when the search finishes the `python asyncio.run(main()) ` closes the loop but aiohttp has some cleanup before the loop closes. And 10 stands there for how many requests will be made at the same time.
> 
> But still if you doesn't want to see error, change
> 
> ```python
> asyncio.run()
> ```
> 
> to
> 
> ```python
> asyncio.get_event_loop().run_until_complete(main())
> ```
> 
> this should fix it

This does fix it but with this method I am unsure if it able to be implemented into discord.py because all the commands are in asynch def methods. 
```@client.command()
async def search(ctx, *, term: str):
    a = asyncio.get_event_loop().run_until_complete(search_links(ctx))
    await ctx.send(a[0])
```
If I try something basic like this to implement it I get this error.
```C:\Users\ahmed\AppData\Local\Programs\Python\Python39\lib\asyncio\events.py:80: RuntimeWarning: coroutine 'search_links' was never awaited
  self._context.run(self._callback, *self._args)
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
```

I tried running the method by adding an await also but that too was unsuccessful. If there is another way to call this method without it crashing or requiring asynchio it would be very much appreciated.

**Comment by Sibyl666** [comment]
If you are using discord py then things get easier. When using discord py you don't have to call event loop or asyncio.run stuff
```python
async def search(ctx, *, term: str):
    async for manga in client.search(term, 1):
        await ctx.send(manga.title)
        break
```
Just for loop is enough you don't need to do anything more
And if you want help faster we can use discord if you want add me Sibyl#3838
